#nullable enable
using System;
using Avalonia.Controls;
using Avalonia.Input;
using Avalonia.Interactivity;
using DawProjectBrowser.Desktop.ViewModels;
using DawProjectBrowser.Desktop.Models; 
using Avalonia.Markup.Xaml;

namespace DawProjectBrowser.Desktop.Views
{
    // Note: The TimelineSlider field is automatically generated by the XAML compiler due to x:Name
    // We must NOT declare it manually here.
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            // The compiler generates the body for InitializeComponent()
            InitializeComponent();
            
            // Add handler to safely dispose the ViewModel when the window closes
            this.Closing += (sender, e) =>
            {
                // Safely call Dispose() on the ViewModel if it implements IDisposable
                (this.DataContext as IDisposable)?.Dispose();
                System.Console.WriteLine("[DEBUG] ViewModel Disposed (Audio cleanup complete).");
            };
        }

        private void InitializeComponent()
        {
            // This call is necessary to wire up the XAML components.
            AvaloniaXamlLoader.Load(this);

            // Find the custom title bar element and attach the event handler defined below
            var titleBar = this.FindControl<Border>("TitleBar");
            if (titleBar != null)
            {
                // Attach the PointerPressed handler only once
                titleBar.PointerPressed += TitleBar_PointerPressed;
            }
            
            // 2. Attach the PointerReleased handler to the generated TimelineSlider field.
            // We use the generated field name directly (TimelineSlider) and check for null.
            if (TimelineSlider != null) 
            {
                TimelineSlider.PointerReleased += TimelineSlider_PointerReleased;
            }
        }

        // --- Custom Title Bar Dragging Logic ---
        /// <summary>
        /// Handles dragging the custom title bar to move the window.
        /// </summary>
        private void TitleBar_PointerPressed(object? sender, PointerPressedEventArgs e)
        {
            // Only start drag if the left mouse button is pressed
            if (e.GetCurrentPoint(this).Properties.IsLeftButtonPressed)
            {
                // Only start drag if the window is not maximized (otherwise the drag will cause issues)
                if (WindowState == Avalonia.Controls.WindowState.Normal)
                {
                    BeginMoveDrag(e);
                }
            }
        }
        
        // Event handler for the clickable DAW image button.
        private void ProjectCardButton_Click(object? sender, RoutedEventArgs e)
        {
            if (sender is Button button && button.DataContext is DawProject clickedProject)
            {
                if (DataContext is ProjectListViewModel viewModel)
                {
                    viewModel.OpenProjectCommand.Execute(clickedProject); 
                    System.Console.WriteLine($"[CODE-BEHIND] Command executed for: {clickedProject.Name}");
                }
            }
        }

        // --- NEW: Event Handler for Timeline Seeking ---
        /// <summary>
        /// Manually executes the SeekCommand when the pointer is released on the slider.
        /// This replaces the Avalonia XAML Behavior that was removed.
        /// </summary>
        private void TimelineSlider_PointerReleased(object? sender, PointerReleasedEventArgs e)
        {
            // Check if we have the ViewModel and the sender is the slider
            if (DataContext is ProjectListViewModel viewModel && sender is Slider slider)
            {
                // The slider value is the CommandParameter
                if (viewModel.SeekCommand.CanExecute(slider.Value))
                {
                    viewModel.SeekCommand.Execute(slider.Value);
                    System.Console.WriteLine($"[CODE-BEHIND] SeekCommand executed with value: {slider.Value}");
                }
            }
        }
        
        // --- NEW: Window Control Logic (Minimize, Maximize, Close) ---
        
        private void CloseButton_Click(object? sender, RoutedEventArgs e)
        {
            // Closes the window
            this.Close();
        }

        private void MinimizeButton_Click(object? sender, RoutedEventArgs e)
        {
            // Sets the window state to minimized
            this.WindowState = WindowState.Minimized;
        }

        private void MaximizeButton_Click(object? sender, RoutedEventArgs e)
        {
            // Toggles between Maximized and Normal state
            if (this.WindowState == WindowState.Maximized)
            {
                this.WindowState = WindowState.Normal;
            }
            else
            {
                this.WindowState = WindowState.Maximized;
            }
        }
    }
}